env_vars:
 "COGNITE_BASE_URL": "https://greenfield.cognitedata.com"
 "COGNITE_PROJECT": "bootcamp-17-test"
 "COGNITE_TOKEN_URL": "https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token"
 "COGNITE_CLIENT_ID": "dc2c1baf-b65a-4e4b-8866-d6919a9d403e"